site_name: Spectrum
repo_url: https://github.com/grokify/spectrum
edit_uri: tree/master/docs
docs_dir: docs
theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: "None"

nav:
    - Home: index.md
    - OpenAPI3Edit:
        - Missing Descriptions: openapi3/inspect/missing_descriptions.md
    - OpenAPI3Lint:
        - Overview: openapi3lint.md
        - Creating Custom Rules: openapi3lint/custom_rules.md
